theme: jekyll-theme-cayman
title: "ATools | Main"
description: [Скрипт сделан для Админов (Normative RP)
Для установки просто закиньте из zip всё в папку moonloader]
show_downloads: "true"
github:
  zip_url: https://factorycraft.ru/lua/atools.zip
